[package]
name = "horst"
version = "0.1.1"
authors = ["anonymous"]
edition = "2018"

[dependencies]
tokio = { version = "1.8", features = ["rt","rt-multi-thread","io-util","time","macros","sync","fs"] }
log = "0.4"
pretty_env_logger = "0.4"
rand = "0.8"
